### ISSUE TITLE
Voter booth

### ISSUE THREAD

**Issue by Aliisza** [m-e-meyer/av-snapshot#9] opened 2024-05-24 11:28 UTC
When running av-snapshot even if you own voter booth and have the "voteAlways" pref set to true. It will change it to false, and not greenbox the voting booth.

**Comment by m-e-meyer** [comment] 2024-05-24 21:25
Thanks for your comment!  The thing is, av-snapshot.ash does not use set_property() at all, so it couldn't be setting your voteAlways to false.  Something else must be going on in your environment.  My own Voting Booth is properly greenboxed.

**Comment by Aliisza** [comment] 2024-05-24 21:31
Huh strange. Cause I do have it, and it was greenboxed at one time. But now when I check the pref for voteAlways I can set it to true. But as soon as I run av-snapshot when it's checking for Mr. Items, it will change it back to false and then it doesn't green.

**Comment by m-e-meyer** [comment] 2024-05-24 23:51
Your current profile _does_ show you having had the voter registration form, so the preference change happens after that preference is read.  Still, av_snapshot.ash doesn't change any properties, so something else is doing that.  I also have Mafia r27956, and I just ran av-snapshot with no issues.  Perhaps Mafia is confused about your Voting Booth.  What would cause that, I wonder.  Do you have any absentee voter ballots?

**Comment by Aliisza** [comment] 2024-05-24 23:53
Apparently it's because when voteToday is true. Mafia sets voteAlways to false.

**Comment by m-e-meyer** [comment] 2024-05-25 02:17
I can confirm what you said (finally - I upgraded my laptop to Fedora 39, and it somehow messed up my local database).  It's not a problem with av_snapshot, but may be a good FAQ candidate.  Thanks for the heads-up!

**Comment by m-e-meyer** [comment] 2024-11-02 17:53
Should have closed this a long time ago, because I added this information to the FAQ already.

**Closed by m-e-meyer** 2024-11-02 17:53 UTC
